<a href="https://colab.research.google.com/github/lekshmilekshmi/ICT_DSA_ACTIVITIES/blob/main/lekshmi_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1.Create a NumPy array

import numpy as np
a = np.arange(10, 50)
print("array:\n",a)
matrix = a.reshape(4, 10)
print("reshaped matrix:\n",matrix)
last_col = matrix[:, -1]
print("last column:\n",last_col)

array:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
reshaped matrix:
 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
last column:
 [19 29 39 49]


In [2]:
# 2.Create two 3×3 matrices:

import numpy as np
A=np.full((3,3),5)
print("5s matrix:\n",A)
B=np.arange(1,10).reshape(3,3)
print("1 to 9 matrix:\n",B)
C=A+B
print("sum of matrices:\n",C)
D=A*B
print("matrix multiplication:\n",D)
transpose=D.T
print("Transpose:\n",transpose)

5s matrix:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
1 to 9 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
sum of matrices:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
matrix multiplication:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
Transpose:
 [[ 5 20 35]
 [10 25 40]
 [15 30 45]]


In [3]:
# 3.Create a NumPy array of 15 random integers between 10 and 100.

import numpy as np
array = np.random.randint(10, 101, 15)
print("array between 10 & 100:",array)
replaced = array > 50
array[replaced] = -1
print("replaced array:",array)
count_replaced = np.sum(replaced)
print("replaced count:\n",count_replaced)



array between 10 & 100: [70 63 91 13 92 81 26 76 21 16 96 33 47 86 81]
replaced array: [-1 -1 -1 13 -1 -1 26 -1 21 16 -1 33 47 -1 -1]
replaced count:
 9


In [4]:
# 4.Generate a 5×4 array with random values between 0 and 1 (float).

import numpy as np
arr4 = np.random.rand(5, 4)
print("Array:\n", arr4)

row_sums = arr4.sum(axis=1)
max_row_index = np.argmax(row_sums)
print("\nRow sums:", row_sums)
print("Row with maximum sum (index):", max_row_index)
print("Row with maximum sum:", arr4[max_row_index])


row_min = arr4.min(axis=1, keepdims=True)
row_max = arr4.max(axis=1, keepdims=True)
normalized_arr = (arr4 - row_min) / (row_max - row_min)

print("\nNormalized Array:\n", normalized_arr)

Array:
 [[0.03732897 0.13427249 0.62694562 0.98277748]
 [0.88777698 0.08451779 0.85598267 0.97505538]
 [0.74689876 0.32456799 0.73589723 0.97288824]
 [0.67902908 0.13211636 0.1199839  0.86574401]
 [0.13382247 0.33922459 0.77818485 0.96683263]]

Row sums: [1.78132456 2.80333282 2.78025222 1.79687335 2.21806453]
Row with maximum sum (index): 1
Row with maximum sum: [0.88777698 0.08451779 0.85598267 0.97505538]

Normalized Array:
 [[0.         0.10253707 0.62363698 1.        ]
 [0.90199358 0.         0.8662912  1.        ]
 [0.65142308 0.         0.6344538  1.        ]
 [0.74963138 0.01626858 0.         1.        ]
 [0.         0.24657817 0.77353483 1.        ]]


In [5]:
# 5.unique elements and duplicates

import numpy as np
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements = np.unique(arr)
unique, counts = np.unique(arr, return_counts=True)
print("Unique elements:", unique_elements)
duplicates = unique[counts > 1]
print("Duplicates:", duplicates)


Unique elements: [1 3 5 7 9]
Duplicates: [1 3 5]


In [6]:
# 6. Create a 6×6 NumPy array with values from 1 to 36

import numpy as np
ar=np.arange(1,37).reshape(6,6)
print("6*6 array:\n",ar)
submatrix = ar[1:5, 1:5]
print("middle 4×4 submatrix:\n",submatrix)
even_no = submatrix[submatrix % 2 == 0]
print("even numbers:",even_no)

6*6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
middle 4×4 submatrix:
 [[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
even numbers: [ 8 10 14 16 20 22 26 28]


In [7]:
# 7.Generate an array of shape (3, 4) with values from 0 to 11.

import numpy as np
ar1=np.arange(0,12).reshape(3,4)
print("array of 3*4:\n",ar1)
reshape = ar1.reshape(2, 6)
print("reshaped:\n",reshape)
flatt = ar1.flatten()
print("Flattened 1D Array:\n", flatt)
ar2 = flatt.reshape(4, 3)
print("Reshaped back to (4x3) Array:\n", ar2)

array of 3*4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshaped:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened 1D Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped back to (4x3) Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [8]:
# 8.Create an array:

import numpy as np
a = np.array([[1, 2],[3, 4]])
a = np.vstack([a, [5, 6]])
a = np.column_stack([a, [7, 8, 9]])
print(a)


[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [9]:
# 9.

import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
arr2 = np.concatenate([a, b, c])
print("Joined array:", arr2)

matrix1 = arr2.reshape(3, 3)
print("3x3 matrix:\n", matrix1)

diag_elements = np.diag(matrix1)
print("Diagonal elements:", diag_elements)

Joined array: [1 2 3 4 5 6 7 8 9]
3x3 matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal elements: [1 5 9]


In [10]:
# 10.Create a NumPy array of integers from 1 to 20.

import numpy as np
arr = np.arange(1, 21)
print("array:", arr)
div = arr[(arr % 3 == 0) | (arr % 5 == 0)]
print("Divisible by 3 or 5:", div)
count = div.size
print("Count:", count)


array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Divisible by 3 or 5: [ 3  5  6  9 10 12 15 18 20]
Count: 9


# **pandas**

In [11]:
# 1.

import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head(10)


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [12]:
#2.
import pandas as pd
missing_values = titanic.isnull().sum()
missing_values


survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [13]:
#3.
import pandas as pd
survival_by_gender = titanic.groupby("sex")["survived"].mean() * 100
survival_by_gender


sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [14]:
#4.
import pandas as pd
avg_age = titanic["age"].mean()
print("Average Age:", avg_age)
median_age = titanic["age"].median()
print("Median Age:", median_age)
std_age = titanic["age"].std()
print("Standard Deviation of Age:", std_age)


Average Age: 29.69911764705882
Median Age: 28.0
Standard Deviation of Age: 14.526497332334044


In [15]:
#5.
class_counts = titanic["pclass"].value_counts()
class_counts

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [16]:
#6.
import pandas as pd
survived = titanic[(titanic["sex"] == "female") & (titanic["age"] < 18) &(titanic["survived"] == 1)]
survived


survived  pclass     sex    age  sibsp  parch      fare embarked   class  \
9           1       2  female  14.00      1      0   30.0708        C  Second   
10          1       3  female   4.00      1      1   16.7000        S   Third   
22          1       3  female  15.00      0      0    8.0292        Q   Third   
39          1       3  female  14.00      1      0   11.2417        C   Third   
43          1       2  female   3.00      1      2   41.5792        C  Second   
58          1       2  female   5.00      1      2   27.7500        S  Second   
68          1       3  female  17.00      4      2    7.9250        S   Third   
84          1       2  female  17.00      0      0   10.5000        S  Second   
156         1       3  female  16.00      0      0    7.7333        Q   Third   
172         1       3  female   1.00      1      1   11.1333        S   Third   
184         1       3  female   4.00      0      2   22.0250        S   Third   
208         1       3  female  16.00      0      0    7.7500        Q   Third   
233         1       3  female   5.00      4      2   31.3875        S   Third   
237         1       2  female   8.00      0      2   26.2500        S  Second   
307         1       1  female  17.00      1      0  108.9000        C   First   
329         1       1  female  16.00      0      1   57.9792        C   First   
381         1       3  female   1.00      0      2   15.7417        C   Third   
389         1       2  female  17.00      0      0   12.0000        C  Second   
435         1       1  female  14.00      1      2  120.0000        S   First   
446         1       2  female  13.00      0      1   19.5000        S  Second   
448         1       3  female   5.00      2      1   19.2583        C   Third   
469         1       3  female   0.75      2      1   19.2583        C   Third   
479         1       3  female   2.00      0      1   12.2875        S   Third   
504         1       1  female  16.00      0      0   86.5000        S   First   
530         1       2  female   2.00      1      1   26.0000        S  Second   
535         1       2  female   7.00      0      2   26.2500        S  Second   
618         1       2  female   4.00      2      1   39.0000        S  Second   
644         1       3  female   0.75      2      1   19.2583        C   Third   
689         1       1  female  15.00      0      1  211.3375        S   First   
691         1       3  female   4.00      0      1   13.4167        C   Third   
720         1       2  female   6.00      0      1   33.0000        S  Second   
750         1       2  female   4.00      1      1   23.0000        S  Second   
777         1       3  female   5.00      0      0   12.4750        S   Third   
780         1       3  female  13.00      0      0    7.2292        C   Third   
781         1       1  female  17.00      1      0   57.0000        S   First   
830         1       3  female  15.00      1      0   14.4542        C   Third   
853         1       1  female  16.00      0      1   39.4000        S   First   
875         1       3  female  15.00      0      0    7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
22   child       False  NaN   Queenstown   yes   True  
39   child       False  NaN    Cherbourg   yes  False  
43   child       False  NaN    Cherbourg   yes  False  
58   child       False  NaN  Southampton   yes  False  
68   woman       False  NaN  Southampton   yes  False  
84   woman       False  NaN  Southampton   yes   True  
156  woman       False  NaN   Queenstown   yes   True  
172  child       False  NaN  Southampton   yes  False  
184  child       False  NaN  Southampton   yes  False  
208  woman       False  NaN   Queenstown   yes   True  
233  child       False  NaN  Southampton   yes  False  
237  child       False  NaN  Southampton   yes  False  
307  

In [17]:
#7.
titanic['age'].fillna(titanic['age'].median(), inplace=True)
print(titanic['age'].isnull().sum())


0


/tmp/ipython-input-4294154388.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['age'].fillna(titanic['age'].median(), inplace=True)


In [18]:
#9.
top_fares = titanic.sort_values(by="fare", ascending=False).head(5)
top_fares

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
679         1       1    male  36.0      0      1  512.3292        C  First   
258         1       1  female  35.0      0      0  512.3292        C  First   
737         1       1    male  35.0      0      0  512.3292        C  First   
88          1       1  female  23.0      3      2  263.0000        S  First   
438         0       1    male  64.0      1      4  263.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
679    man        True    B    Cherbourg   yes  False  
258  woman       False  NaN    Cherbourg   yes   True  
737    man        True    B    Cherbourg   yes   True  
88   woman       False    C  Southampton   yes  False  
438    man        True    C  Southampton    no  False

In [19]:
#10.
avg_fare = titanic.groupby(["pclass", "sex"])["fare"].mean()
print(avg_fare)

pclass  sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: fare, dtype: float64


In [20]:
#11.
titanic.rename(columns={'sex': 'gender', 'fare': 'ticket_fare'}, inplace=True)
print(titanic.head())

   survived  pclass  gender   age  sibsp  parch  ticket_fare embarked  class  \
0         0       3    male  22.0      1      0       7.2500        S  Third   
1         1       1  female  38.0      1      0      71.2833        C  First   
2         1       3  female  26.0      0      0       7.9250        S  Third   
3         1       1  female  35.0      1      0      53.1000        S  First   
4         0       3    male  35.0      0      0       8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [22]:
#13.
avg_age_grouped = titanic.groupby(["pclass", "gender"])["age"].mean()
print(avg_age_grouped)

pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: age, dtype: float64
